stages:
  - node14
  - latest

cache:
  paths:
    - node_modules/

node_14:
  stage: node14
  image: node:14
  script: 
    - npm install
    - npm test
  artifacts:
    paths:
      - coverage
  coverage: /Statements\s+:\s(\d+.?\d+)%/

node_latest:
  stage: latest
  image: node:latest
  script: 
    - npm install
    - npm test
  artifacts:
    paths:
      - coverage
  coverage: /Statements\s+:\s(\d+.?\d+)%/